name: 'fakeschool_dbt'
version: '1.0.0'
profile: 'fakeschool_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]

seeds:
  fakeschool_dbt:


models:
  fakeschool_dbt:
    silver:
      +materialized: incremental  
    gold:
      +materialized: view
