name: Analyze Gold & Generate Charts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  generate-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas matplotlib snowflake-connector-python

    - name: Run gold queries & generate charts
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      run: python generate_gold_graphs.py

    - name: Zip charts
      run: zip -r gold_charts.zip charts/

    - name: Upload charts as artifact
      uses: actions/upload-artifact@v4
      with:
        name: gold-charts
        path: gold_charts.zip
