name: Run Snowflake Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib snowflake-connector-python

    - name: Run analysis script
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: python analyze_results.py
      working-directory: ./  # <- Dossier où se trouve analyze_results.py

      name: Run Snowflake Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib snowflake-connector-python

    - name: Run analysis script
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: python analyze_results.py
      working-directory: ./  # Dossier où se trouve analyze_results.py

    - name: Upload analysis artifacts
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: |
          average_grades_chart.png
          grade_distribution_chart.png

